"use client";

import {
  CircleDollarSign,
  Gift,
  TrendingUp,
  Search,
} from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type Earning = {
  id: string;
  amount: number;
  percentage: number;
  transactionAmount: number;
  type: string;
  status: string;
  description: string | null;
  reference: string;
  createdAt: string;

  referrer: {
    id: string;
    fullName: string | null;
    email: string;
    referralCode: string | null;
  } | null;

  referredUser: {
    id: string;
    fullName: string | null;
    email: string;
  } | null;
};

function formatMoney(value: number) {
  return `₦${value.toLocaleString("en-NG", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;
}

export default function ReferralEarningsPage() {
  const [earnings, setEarnings] = useState<Earning[]>(
    []
  );

  const [loading, setLoading] =
    useState(true);

  const [search, setSearch] =
    useState("");

  async function loadEarnings() {
    try {
      setLoading(true);

      const response = await fetch(
        "/api/admin/referral/earnings",
        {
          cache: "no-store",
        }
      );

      const data = await response.json();

      if (!response.ok || !data.success) {
        throw new Error(
          data.message ||
            "Unable to load referral earnings."
        );
      }

      setEarnings(
        data.earnings || []
      );
    } catch (error) {
      console.error(
        "LOAD REFERRAL EARNINGS ERROR:",
        error
      );
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    loadEarnings();
  }, []);

  const filtered = useMemo(() => {
    const value =
      search.trim().toLowerCase();

    if (!value) return earnings;

    return earnings.filter(
      (earning) =>
        earning.referrer?.fullName
          ?.toLowerCase()
          .includes(value) ||
        earning.referrer?.email
          ?.toLowerCase()
          .includes(value) ||
        earning.referrer?.referralCode
          ?.toLowerCase()
          .includes(value) ||
        earning.reference
          ?.toLowerCase()
          .includes(value)
    );
  }, [earnings, search]);

  const total = earnings.reduce(
    (sum, earning) =>
      sum + earning.amount,
    0
  );

  const successful = earnings
    .filter(
      (earning) =>
        earning.status === "SUCCESS"
    )
    .reduce(
      (sum, earning) =>
        sum + earning.amount,
      0
    );

  const average =
    earnings.length > 0
      ? total / earnings.length
      : 0;

  return (
    <div className="space-y-6">
      {/* HEADER */}

      <div className="pl-14 lg:pl-0">
        <p className="text-sm font-semibold text-indigo-600">
          Referral System
        </p>

        <h1 className="mt-1 text-2xl font-bold text-gray-900 sm:text-3xl">
          Referral Earnings
        </h1>

        <p className="mt-2 text-sm text-gray-500 sm:text-base">
          Track every referral commission
          generated by your users.
        </p>
      </div>

      {/* STATS */}

      <div className="grid gap-4 sm:grid-cols-3">
        <div className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm">
          <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-indigo-100">
            <CircleDollarSign className="h-5 w-5 text-indigo-600" />
          </div>

          <p className="mt-4 text-sm text-gray-500">
            Total Earnings
          </p>

          <p className="mt-1 text-2xl font-bold text-gray-900">
            {formatMoney(total)}
          </p>
        </div>

        <div className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm">
          <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-green-100">
            <TrendingUp className="h-5 w-5 text-green-600" />
          </div>

          <p className="mt-4 text-sm text-gray-500">
            Successful Earnings
          </p>

          <p className="mt-1 text-2xl font-bold text-green-600">
            {formatMoney(successful)}
          </p>
        </div>

        <div className="rounded-2xl border border-gray-100 bg-white p-5 shadow-sm">
          <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-purple-100">
            <Gift className="h-5 w-5 text-purple-600" />
          </div>

          <p className="mt-4 text-sm text-gray-500">
            Average Commission
          </p>

          <p className="mt-1 text-2xl font-bold text-gray-900">
            {formatMoney(average)}
          </p>
        </div>
      </div>

      {/* SEARCH */}

      <div className="rounded-2xl border border-gray-100 bg-white p-4 shadow-sm">
        <div className="relative">
          <Search className="absolute left-3.5 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-400" />

          <input
            value={search}
            onChange={(event) =>
              setSearch(event.target.value)
            }
            placeholder="Search referrer, email, code or reference..."
            className="h-12 w-full rounded-xl border border-gray-200 bg-gray-50 pl-11 pr-4 text-sm outline-none transition focus:border-indigo-500 focus:bg-white focus:ring-4 focus:ring-indigo-500/10"
          />
        </div>
      </div>

      {/* TABLE */}

      <div className="overflow-hidden rounded-2xl border border-gray-100 bg-white shadow-sm">
        {loading ? (
          <div className="p-10 text-center text-sm text-gray-500">
            Loading earnings...
          </div>
        ) : filtered.length === 0 ? (
          <div className="p-10 text-center">
            <Gift className="mx-auto h-10 w-10 text-gray-300" />

            <p className="mt-3 font-semibold text-gray-900">
              No referral earnings found
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="min-w-[1100px] w-full">
              <thead className="border-b border-gray-100 bg-gray-50">
                <tr className="text-left text-xs font-bold uppercase tracking-wider text-gray-500">
                  <th className="px-5 py-4">
                    Referrer
                  </th>

                  <th className="px-5 py-4">
                    Referred User
                  </th>

                  <th className="px-5 py-4">
                    Transaction
                  </th>

                  <th className="px-5 py-4">
                    Rate
                  </th>

                  <th className="px-5 py-4">
                    Commission
                  </th>

                  <th className="px-5 py-4">
                    Status
                  </th>

                  <th className="px-5 py-4">
                    Date
                  </th>
                </tr>
              </thead>

              <tbody className="divide-y divide-gray-100">
                {filtered.map(
                  (earning) => (
                    <tr
                      key={earning.id}
                      className="transition hover:bg-gray-50"
                    >
                      <td className="px-5 py-4">
                        <p className="font-semibold text-gray-900">
                          {earning.referrer
                            ?.fullName ||
                            "Unknown"}
                        </p>

                        <p className="mt-1 text-xs text-gray-500">
                          {earning.referrer
                            ?.email}
                        </p>

                        <p className="mt-1 text-xs font-bold text-indigo-600">
                          {earning.referrer
                            ?.referralCode ||
                            "N/A"}
                        </p>
                      </td>

                      <td className="px-5 py-4">
                        <p className="font-medium text-gray-800">
                          {earning
                            .referredUser
                            ?.fullName ||
                            "Unknown"}
                        </p>

                        <p className="mt-1 text-xs text-gray-500">
                          {earning
                            .referredUser
                            ?.email}
                        </p>
                      </td>

                      <td className="px-5 py-4">
                        <p className="font-semibold text-gray-900">
                          {formatMoney(
                            earning.transactionAmount
                          )}
                        </p>

                        <p className="mt-1 text-xs text-gray-500">
                          {earning.type}
                        </p>
                      </td>

                      <td className="px-5 py-4">
                        <span className="rounded-full bg-indigo-50 px-3 py-1 text-xs font-bold text-indigo-700">
                          {earning.percentage}%
                        </span>
                      </td>

                      <td className="px-5 py-4">
                        <span className="font-bold text-green-600">
                          {formatMoney(
                            earning.amount
                          )}
                        </span>
                      </td>

                      <td className="px-5 py-4">
                        <span
                          className={`rounded-full px-3 py-1 text-xs font-bold ${
                            earning.status ===
                            "SUCCESS"
                              ? "bg-green-100 text-green-700"
                              : earning.status ===
                                "PENDING"
                              ? "bg-yellow-100 text-yellow-700"
                              : "bg-red-100 text-red-700"
                          }`}
                        >
                          {earning.status}
                        </span>
                      </td>

                      <td className="px-5 py-4 text-sm text-gray-500">
                        {new Date(
                          earning.createdAt
                        ).toLocaleString(
                          "en-NG"
                        )}
                      </td>
                    </tr>
                  )
                )}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}