import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const plans = [
  // =========================
  // AIRTEL
  // =========================
  {
    provider: "AIRTEL",
    bundleId: 70,
    name: "Airtel 1GB Social Bundle",
    size: "1GB",
    duration: "3 Days",
    providerPrice: 295,
    sellingPrice: 350,
  },
  {
    provider: "AIRTEL",
    bundleId: 13,
    name: "Airtel 500MB",
    size: "500MB",
    duration: "7 Days",
    providerPrice: 490,
    sellingPrice: 550,
  },
  {
    provider: "AIRTEL",
    bundleId: 69,
    name: "Airtel 1.5GB",
    size: "1.5GB",
    duration: "1 Day",
    providerPrice: 500,
    sellingPrice: 550,
  },
  {
    provider: "AIRTEL",
    bundleId: 66,
    name: "Airtel 1.5GB",
    size: "1.5GB",
    duration: "2 Days",
    providerPrice: 599,
    sellingPrice: 650,
  },
  {
    provider: "AIRTEL",
    bundleId: 15,
    name: "Airtel 1GB",
    size: "1GB",
    duration: "7 Days",
    providerPrice: 800,
    sellingPrice: 850,
  },
  {
    provider: "AIRTEL",
    bundleId: 17,
    name: "Airtel 2GB",
    size: "2GB",
    duration: "30 Days",
    providerPrice: 1490,
    sellingPrice: 1600,
  },
  {
    provider: "AIRTEL",
    bundleId: 52,
    name: "Airtel 5GB",
    size: "5GB",
    duration: "7 Days",
    providerPrice: 1570,
    sellingPrice: 1650,
  },
  {
    provider: "AIRTEL",
    bundleId: 18,
    name: "Airtel 3GB",
    size: "3GB",
    duration: "30 Days",
    providerPrice: 1960,
    sellingPrice: 2100,
  },
  {
    provider: "AIRTEL",
    bundleId: 22,
    name: "Airtel 6GB",
    size: "6GB",
    duration: "7 Days",
    providerPrice: 2455,
    sellingPrice: 2600,
  },
  {
    provider: "AIRTEL",
    bundleId: 19,
    name: "Airtel 4GB",
    size: "4GB",
    duration: "30 Days",
    providerPrice: 2570,
    sellingPrice: 2700,
  },
  {
    provider: "AIRTEL",
    bundleId: 20,
    name: "Airtel 8GB",
    size: "8GB",
    duration: "30 Days",
    providerPrice: 2999,
    sellingPrice: 3200,
  },
  {
    provider: "AIRTEL",
    bundleId: 21,
    name: "Airtel 10GB",
    size: "10GB",
    duration: "30 Days",
    providerPrice: 4070,
    sellingPrice: 4300,
  },

  // =========================
  // GLO
  // =========================
  {
    provider: "GLO",
    bundleId: 42,
    name: "Glo 200MB",
    size: "200MB",
    duration: "1 Day",
    providerPrice: 92,
    sellingPrice: 100,
  },
  {
    provider: "GLO",
    bundleId: 35,
    name: "Glo 500MB",
    size: "500MB",
    duration: "30 Days",
    providerPrice: 225,
    sellingPrice: 250,
  },
  {
    provider: "GLO",
    bundleId: 68,
    name: "Glo 1GB",
    size: "1GB",
    duration: "3 Days",
    providerPrice: 300,
    sellingPrice: 350,
  },
  {
    provider: "GLO",
    bundleId: 36,
    name: "Glo 1GB",
    size: "1GB",
    duration: "30 Days",
    providerPrice: 425,
    sellingPrice: 450,
  },
  {
    provider: "GLO",
    bundleId: 41,
    name: "Glo 1GB",
    size: "1GB",
    duration: "14 Days",
    providerPrice: 485,
    sellingPrice: 500,
  },
  {
    provider: "GLO",
    bundleId: 40,
    name: "Glo 2GB",
    size: "2GB",
    duration: "30 Days",
    providerPrice: 850,
    sellingPrice: 900,
  },
  {
    provider: "GLO",
    bundleId: 37,
    name: "Glo 3GB",
    size: "3GB",
    duration: "30 Days",
    providerPrice: 1300,
    sellingPrice: 1400,
  },
  {
    provider: "GLO",
    bundleId: 54,
    name: "Glo 5GB",
    size: "5GB",
    duration: "7 Days",
    providerPrice: 1699,
    sellingPrice: 1800,
  },
  {
    provider: "GLO",
    bundleId: 38,
    name: "Glo 5GB",
    size: "5GB",
    duration: "30 Days",
    providerPrice: 2250,
    sellingPrice: 2400,
  },
  {
    provider: "GLO",
    bundleId: 39,
    name: "Glo 10GB",
    size: "10GB",
    duration: "30 Days",
    providerPrice: 4390,
    sellingPrice: 4600,
  },
  {
    provider: "GLO",
    bundleId: 59,
    name: "Glo 20.5GB",
    size: "20.5GB",
    duration: "30 Days",
    providerPrice: 5300,
    sellingPrice: 5500,
  },
  {
    provider: "GLO",
    bundleId: 58,
    name: "Glo 107GB",
    size: "107GB",
    duration: "30 Days",
    providerPrice: 19300,
    sellingPrice: 20000,
  },

  // =========================
  // MTN
  // =========================
  {
    provider: "MTN",
    bundleId: 43,
    name: "MTN 110MB",
    size: "110MB",
    duration: "1 Day",
    providerPrice: 99,
    sellingPrice: 100,
  },
  {
    provider: "MTN",
    bundleId: 74,
    name: "MTN 230MB",
    size: "230MB",
    duration: "1 Day",
    providerPrice: 200,
    sellingPrice: 250,
  },
  {
    provider: "MTN",
    bundleId: 76,
    name: "MTN 500MB",
    size: "500MB",
    duration: "2 Days",
    providerPrice: 250,
    sellingPrice: 270,
  },
  {
    provider: "MTN",
    bundleId: 78,
    name: "MTN 1GB",
    size: "1GB",
    duration: "1 Day",
    providerPrice: 270,
    sellingPrice: 300,
  },
  {
    provider: "MTN",
    bundleId: 81,
    name: "MTN 1GB",
    size: "1GB",
    duration: "30 Days",
    providerPrice: 280,
    sellingPrice: 350,
  },
  {
    provider: "MTN",
    bundleId: 44,
    name: "MTN 500MB",
    size: "500MB",
    duration: "30 Days",
    providerPrice: 350,
    sellingPrice: 400,
  },
  {
    provider: "MTN",
    bundleId: 77,
    name: "MTN 1GB",
    size: "1GB",
    duration: "2 Days",
    providerPrice: 399,
    sellingPrice: 450,
  },
  {
    provider: "MTN",
    bundleId: 45,
    name: "MTN 1GB",
    size: "1GB",
    duration: "7 Days",
    providerPrice: 450,
    sellingPrice: 500,
  },
  {
    provider: "MTN",
    bundleId: 46,
    name: "MTN 1GB",
    size: "1GB",
    duration: "30 Days",
    providerPrice: 570,
    sellingPrice: 600,
  },
  {
    provider: "MTN",
    bundleId: 79,
    name: "MTN 2.5GB",
    size: "2.5GB",
    duration: "1 Day",
    providerPrice: 600,
    sellingPrice: 650,
  },
  {
    provider: "MTN",
    bundleId: 47,
    name: "MTN 2GB",
    size: "2GB",
    duration: "7 Days",
    providerPrice: 930,
    sellingPrice: 1000,
  },
  {
    provider: "MTN",
    bundleId: 27,
    name: "MTN 2.5GB",
    size: "2.5GB",
    duration: "2 Days",
    providerPrice: 900,
    sellingPrice: 1000,
  },
  {
    provider: "MTN",
    bundleId: 71,
    name: "MTN 2GB",
    size: "2GB",
    duration: "7 Days",
    providerPrice: 900,
    sellingPrice: 1000,
  },
  {
    provider: "MTN",
    bundleId: 60,
    name: "MTN 4.5GB",
    size: "4.5GB",
    duration: "1 Day",
    providerPrice: 1050,
    sellingPrice: 1100,
  },
  {
    provider: "MTN",
    bundleId: 48,
    name: "MTN 2GB",
    size: "2GB",
    duration: "30 Days",
    providerPrice: 1150,
    sellingPrice: 1250,
  },
  {
    provider: "MTN",
    bundleId: 61,
    name: "MTN 4GB",
    size: "4GB",
    duration: "2 Days",
    providerPrice: 1175,
    sellingPrice: 1300,
  },
  {
    provider: "MTN",
    bundleId: 82,
    name: "MTN 5GB",
    size: "5GB",
    duration: "30 Days",
    providerPrice: 1299,
    sellingPrice: 1500,
  },
  {
    provider: "MTN",
    bundleId: 80,
    name: "MTN 5GB",
    size: "5GB",
    duration: "14 Days",
    providerPrice: 1299,
    sellingPrice: 1500,
  },
  {
    provider: "MTN",
    bundleId: 49,
    name: "MTN 3GB",
    size: "3GB",
    duration: "30 Days",
    providerPrice: 1370,
    sellingPrice: 1500,
  },
  {
    provider: "MTN",
    bundleId: 50,
    name: "MTN 5GB",
    size: "5GB",
    duration: "30 Days",
    providerPrice: 2050,
    sellingPrice: 2300,
  },
  {
    provider: "MTN",
    bundleId: 53,
    name: "MTN 6GB",
    size: "6GB",
    duration: "7 Days",
    providerPrice: 2495,
    sellingPrice: 2600,
  },
  {
    provider: "MTN",
    bundleId: 55,
    name: "MTN 11GB",
    size: "11GB",
    duration: "7 Days",
    providerPrice: 3550,
    sellingPrice: 3600,
  },
  {
    provider: "MTN",
    bundleId: 33,
    name: "MTN 7GB",
    size: "7GB",
    duration: "30 Days",
    providerPrice: 3600,
    sellingPrice: 3800,
  },
  {
    provider: "MTN",
    bundleId: 67,
    name: "MTN 10GB",
    size: "10GB",
    duration: "30 Days",
    providerPrice: 4800,
    sellingPrice: 5000,
  },
  {
    provider: "MTN",
    bundleId: 57,
    name: "MTN 36GB",
    size: "36GB",
    duration: "30 Days",
    providerPrice: 10900,
    sellingPrice: 11000,
  },
  {
    provider: "MTN",
    bundleId: 51,
    name: "MTN 75GB",
    size: "75GB",
    duration: "30 Days",
    providerPrice: 17990,
    sellingPrice: 18500,
  },
];

async function main() {
  console.log(`Preparing ${plans.length} data plans...`);

  for (const plan of plans) {
    await prisma.dataPlan.upsert({
      where: {
        bundleId: plan.bundleId,
      },
      update: {
        provider: plan.provider,
        name: plan.name,
        size: plan.size,
        duration: plan.duration,
        providerPrice: plan.providerPrice,
        // Keep existing admin selling price if the plan already exists.
        // New plans receive the initial selling price above.
        status: "ACTIVE",
      },
      create: {
        provider: plan.provider,
        bundleId: plan.bundleId,
        name: plan.name,
        size: plan.size,
        duration: plan.duration,
        providerPrice: plan.providerPrice,
        sellingPrice: plan.sellingPrice,
        status: "ACTIVE",
      },
    });
  }

  console.log("Data plans successfully inserted.");
}

main()
  .catch((error) => {
    console.error("SEED ERROR:", error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });